### PR TITLE
Gnuradio test [Launching App]

### PR DESCRIPTION
**Pull request by cseptimo**
This test is a checker for Gnuradio Companion Application.

- Create host display
- Open the application
- Check if the launched application is accurate.
- Screenshot the result then check the reference image.

### CODE REVIEW

**Comment by kimpaller** [comment]
@cseptimo Might be better to squash minor changes into one commit and group similar functions/features into one commit to reduce commit floods.,

**Comment by tagoylo** [comment]
I see files for iio oscilloscope as well, are they intended to be part of this PR?

**Comment by cseptimo** [comment]
@kimpaller, this is acknowledged.

**Comment by cseptimo** [comment]
@tagoylo, I edited the description for this PR, which includes the iio-osc; this will not affect the testing for gnuradio.

**Comment by tagoylo** [comment]
Are the iio osc test done and working to be part of this PR? If not, it is better to not include them since this PR states for GNU radio tests.

**Comment by cseptimo** [comment]
Creating new branch for kuiper linux application tests feature.

**Pull request closed without merging**
